#!/bin/bash

GITCONFIG=~/.gitconfig

if [ -d "$GITCONFIG" ] || [ -L "$GITCONFIG" ]; then
    echo "$GITCONFIG" is not a regular file.
    exit 1
fi

echo \# Generated by $(basename "$0") >"$GITCONFIG" || {
    echo Cannot write to "$GITCONFIG"
    exit 1
}

git config -f 'gitconfig' --includes -l | while IFS== read key value
do
    if [ "$key" = 'include.path' ]; then
        continue
    fi

    git config -f "$GITCONFIG" $key "$value"
done
